### PR TITLE
load_boston no longer in scikit

### PR DESCRIPTION
**Pull request by danbills**
Scikit-learn removed `load_boston` from the library, but helpfully added a workaround within the doc, pasted below.

This PR incorporates the workaround.  I have tested it and it works as expected.

```
`load_boston` has been removed from scikit-learn since version 1.2.

            The Boston housing prices dataset has an ethical problem: as
            investigated in [1], the authors of this dataset engineered a
            non-invertible variable "B" assuming that racial self-segregation had a
            positive impact on house prices [2]. Furthermore the goal of the
            research that led to the creation of this dataset was to study the
            impact of air quality but it did not give adequate demonstration of the
            validity of this assumption.

            The scikit-learn maintainers therefore strongly discourage the use of
            this dataset unless the purpose of the code is to study and educate
            about ethical issues in data science and machine learning.

            In this special case, you can fetch the dataset from the original
            source::

                import pandas as pd
                import numpy as np

                data_url = "http://lib.stat.cmu.edu/datasets/boston"
                raw_df = pd.read_csv(data_url, sep="\\s+", skiprows=22, header=None)
                data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
                target = raw_df.values[1::2, 2]

            Alternative datasets include the California housing dataset and the
            Ames housing dataset. You can load the datasets as follows::

                from sklearn.datasets import fetch_california_housing
                housing = fetch_california_housing()

            for the California housing dataset and::

                from sklearn.datasets import fetch_openml
                housing = fetch_openml(name="house_prices", as_frame=True)

            for the Ames housing dataset.

            [1] M Carlisle.
            "Racist data destruction?"
            <https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

            [2] Harrison Jr, David, and Daniel L. Rubinfeld.
            "Hedonic housing prices and the demand for clean air."
            Journal of environmental economics and management 5.1 (1978): 81-102.
            <https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>
```

### CODE REVIEW

**Comment by magnus-ekman** [comment]
Thanks. This looks like a good solution. It seems like your change only addresses the problem in the .py file but not in the .ipynb file (the notebook version). Do you prefer that I accept the pull request and then do my own equivalent change to the .ipynb file, or do you prefer to modify the pull request to also fix the notebook? I'm fine with either.

**Comment by magnus-ekman** [comment]
I realized that this change also needs to be applied to the other code example from the same chapter. I.e., all in all, the following four files need the fix:
c6e1_boston.py
c6e1_boston.ipynb
c6e2_boston_conf6.py
c6e2_boston_conf6.ipynb

**Comment by danbills** [comment]
Ok I'll fix those files up too

**Comment by danbills** [comment]
@magnus-ekman I've pushed updates that I've tested locally.

**Comment by magnus-ekman** [comment]
Thanks! I'll try to find time later this week to test this.

**Comment by magnus-ekman** [comment]
This pull request is now merged. Thanks for contributing!

**Pull request merged**
